"""autogen update

Revision ID: 06cb3b12e19c
Revises: 880b84f7f207
Create Date: 2025-11-17 00:01:53.756639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '06cb3b12e19c'
down_revision: Union[str, Sequence[str], None] = '880b84f7f207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'is_air_unit')
    op.drop_column('units', 'need_water_neighbor_for_spawn')
    op.drop_column('units', 'is_water_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('is_water_unit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('units', sa.Column('need_water_neighbor_for_spawn', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('units', sa.Column('is_air_unit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
