"""autogen update

Revision ID: 4d5706b3c424
Revises: 723a60952144
Create Date: 2025-11-11 23:33:57.249093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5706b3c424'
down_revision: Union[str, Sequence[str], None] = '723a60952144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_maps', sa.Column('max_players', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_maps', 'max_players')
    # ### end Alembic commands ###
