"""autogen update

Revision ID: 6e6f24110f7d
Revises: 
Create Date: 2025-11-12 21:47:10.814215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6f24110f7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('country_list', sa.JSON(), nullable=False),
    sa.Column('available_states', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=6), nullable=True),
    sa.Column('is_supply_point', sa.Boolean(), nullable=False),
    sa.Column('is_water', sa.Boolean(), nullable=False),
    sa.Column('neighbors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('movement_point', sa.Integer(), nullable=True),
    sa.Column('need_water_neighbor_for_spawn', sa.Boolean(), nullable=True),
    sa.Column('is_air_unit', sa.Boolean(), nullable=True),
    sa.Column('is_water_unit', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('first_login', sa.Integer(), nullable=False),
    sa.Column('last_activity', sa.Integer(), nullable=False),
    sa.Column('last_password_change', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('banned_to', sa.Integer(), nullable=True),
    sa.Column('banned_reason', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=255), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('capital_state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['capital_state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_matches',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('map', sa.Integer(), nullable=True),
    sa.Column('owner', sa.VARCHAR(length=36), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('current_year', sa.Integer(), nullable=True),
    sa.Column('current_month', sa.Integer(), nullable=True),
    sa.Column('turn', sa.Integer(), nullable=True),
    sa.Column('in_game_player', sa.JSON(), nullable=True),
    sa.Column('country', sa.JSON(), nullable=True),
    sa.Column('states', sa.JSON(), nullable=True),
    sa.Column('units', sa.JSON(), nullable=True),
    sa.Column('game_code', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['map'], ['game_maps.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('game_code')
    )
    op.create_table('battle_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('player_uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('current_year', sa.Integer(), nullable=True),
    sa.Column('current_month', sa.Integer(), nullable=True),
    sa.Column('turn', sa.Integer(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('target_state', sa.Integer(), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=36), nullable=True),
    sa.Column('target_unit', sa.VARCHAR(length=36), nullable=True),
    sa.Column('action_result', sa.VARCHAR(length=10), nullable=True),
    sa.Column('service_information', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['match_uuid'], ['game_matches.uuid'], ),
    sa.ForeignKeyConstraint(['player_uuid'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['state'], ['states.id'], ),
    sa.ForeignKeyConstraint(['target_state'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('target_state_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=36), nullable=True),
    sa.Column('target_unit', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['match_uuid'], ['game_matches.uuid'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['target_state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_action')
    op.drop_table('battle_history')
    op.drop_table('game_matches')
    op.drop_table('country')
    op.drop_table('users')
    op.drop_table('units')
    op.drop_table('states')
    op.drop_table('game_maps')
    # ### end Alembic commands ###
