"""autogen update

Revision ID: 880b84f7f207
Revises: 897c4ad89d43
Create Date: 2025-11-17 00:01:14.588600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880b84f7f207'
down_revision: Union[str, Sequence[str], None] = '897c4ad89d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('type', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'type')
    # ### end Alembic commands ###
