"""autogen update

Revision ID: 897c4ad89d43
Revises: 6e6f24110f7d
Create Date: 2025-11-16 23:54:41.183490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897c4ad89d43'
down_revision: Union[str, Sequence[str], None] = '6e6f24110f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('defence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'defence')
    # ### end Alembic commands ###
