"""autogen update

Revision ID: bc91f588ed18
Revises: c686f834bbcb
Create Date: 2025-11-12 17:06:47.813915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bc91f588ed18'
down_revision: Union[str, Sequence[str], None] = 'c686f834bbcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('neighbors', sa.JSON(), nullable=False))
    op.drop_column('states', 'neighbor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('neighbor', mysql.JSON(), nullable=False))
    op.drop_column('states', 'neighbors')
    # ### end Alembic commands ###
