"""autogen update

Revision ID: c686f834bbcb
Revises: 4d5706b3c424
Create Date: 2025-11-12 16:54:35.519972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c686f834bbcb'
down_revision: Union[str, Sequence[str], None] = '4d5706b3c424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_maps', 'name',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('game_maps', 'max_players',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('game_maps', 'country_list',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('game_maps', 'available_states',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('states', 'is_supply_point',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('states', 'is_water',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('states', 'neighbor',
               existing_type=mysql.JSON(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('states', 'neighbor',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('states', 'is_water',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('states', 'is_supply_point',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('game_maps', 'available_states',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('game_maps', 'country_list',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('game_maps', 'max_players',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('game_maps', 'name',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
